# Generated by Django 5.2.4 on 2025-11-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_user_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', 'Master - Full Access'), ('manager', 'Manager - Admin Access'), ('operator', 'Operator - Standard Access'), ('field', 'Field - Limited Access'), ('readonly', 'Read-Only Access')], default='operator', max_length=20),
        ),
    ]
