# Generated by Django 5.2.4 on 2025-10-30 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_docs', '0007_alter_legaltemplate_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legaltemplate',
            name='last_completion_date',
            field=models.DateField(blank=True, help_text='Date when obligation was last completed', null=True),
        ),
        migrations.AddField(
            model_name='legaltemplate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LegalObligationCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('previous_due_date', models.DateField(blank=True, null=True)),
                ('new_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='legal_docs.legaltemplate')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
    ]
