# Generated by Django 5.2.4 on 2025-12-05 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_docs', '0008_legaltemplate_last_completion_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('building_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use'), ('industrial', 'Industrial')], max_length=20, null=True)),
                ('frequency', models.CharField(default='annual', max_length=50)),
                ('conditions', models.TextField(blank=True)),
                ('requires_quote', models.BooleanField(default=False)),
                ('notice_period', models.IntegerField(default=14, help_text='Notice period in days')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this obligation has been activated for buildings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obligation Library Entry',
                'verbose_name_plural': 'Obligation Library',
                'ordering': ['name'],
            },
        ),
    ]
