# Generated by Django 5.2.4 on 2025-12-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_docs', '0009_add_obligation_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaltemplate',
            name='observations',
            field=models.TextField(blank=True, help_text='Additional observations or notes'),
        ),
    ]
