# Generated by Django 5.2.4 on 2025-11-30 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0012_alter_unit_unique_together'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page3_financial_justification', models.TextField(blank=True, default='')),
                ('page4_income_justification', models.TextField(blank=True, default='')),
                ('page4_expenses_justification', models.TextField(blank=True, default='')),
                ('page4_balance_justification', models.TextField(blank=True, default='')),
                ('page5_section1_justification', models.TextField(blank=True, default='')),
                ('page5_section2_justification', models.TextField(blank=True, default='')),
                ('page5_section3_justification', models.TextField(blank=True, default='')),
                ('page6_market_value_justification', models.TextField(blank=True, default='')),
                ('page7_legal_justification', models.TextField(blank=True, default='')),
                ('page8_consumption_justification', models.TextField(blank=True, default='')),
                ('page9_requests_justification', models.TextField(blank=True, default='')),
                ('page10_calendar_justification', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_justifications', to='building_mgmt.building')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Justification',
                'verbose_name_plural': 'Report Justifications',
            },
        ),
    ]
