# Generated by Django 5.2.4 on 2025-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_reportjustification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportjustification',
            name='page8_consumption_justification',
        ),
        migrations.AddField(
            model_name='reportjustification',
            name='page8_electricity_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportjustification',
            name='page8_gas_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportjustification',
            name='page8_water_justification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
