# Generated by Django 5.2.4 on 2025-11-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_remove_reportjustification_page8_consumption_justification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportjustification',
            name='page6_market_value_justification',
        ),
    ]
