# Generated by Django 5.2.4 on 2025-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_remove_reportjustification_page6_market_value_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjustification',
            name='page5_section4_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportjustification',
            name='page5_section5_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportjustification',
            name='page5_section6_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportjustification',
            name='page5_section7_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportjustification',
            name='page5_section8_justification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
