# Generated by Django 5.2.4 on 2025-12-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_reportjustification_page5_section4_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjustification',
            name='page3_balances_justification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
