# Generated by Django 5.2.4 on 2025-10-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0012_alter_unit_unique_together'),
        ('financials', '0003_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_month', models.CharField(max_length=7)),
                ('end_month', models.CharField(max_length=7)),
                ('fiscal_year_start', models.CharField(max_length=7)),
                ('fiscal_year_end', models.CharField(max_length=7)),
                ('is_extended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_accounts', to='building_mgmt.building')),
            ],
            options={
                'db_table': 'financials_revenue_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_account', models.CharField(choices=[('personnel_and_charges', 'Personnel and Charges'), ('fees_and_public_taxes', 'Fees and Public Taxes'), ('contracts', 'Contracts'), ('maintenance', 'Maintenance'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('account_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_month', models.CharField(max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_outside_fiscal_period', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='building_mgmt.building')),
            ],
            options={
                'db_table': 'financials_expense_entry',
                'ordering': ['-reference_month', '-created_at'],
                'indexes': [models.Index(fields=['building', 'reference_month'], name='financials__buildin_4bfd05_idx'), models.Index(fields=['parent_account'], name='financials__parent__eeb71f_idx')],
            },
        ),
    ]
