# Generated by Django 5.2.4 on 2025-10-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0012_alter_unit_unique_together'),
        ('financials', '0004_revenueaccount_expenseentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_month', models.CharField(max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='building_mgmt.building')),
            ],
            options={
                'db_table': 'financials_additional_charge',
                'ordering': ['-reference_month', '-created_at'],
                'indexes': [models.Index(fields=['building', 'reference_month'], name='financials__buildin_7ac027_idx'), models.Index(fields=['active'], name='financials__active_62b1a6_idx')],
            },
        ),
    ]
