# Generated by Django 5.2.4 on 2025-10-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_additionalcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueaccount',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_accounts', to='financials.financialmainaccount'),
        ),
    ]
