# Generated by Django 5.2.4 on 2025-10-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_revenueaccount_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmainaccount',
            name='assembly_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmainaccount',
            name='assembly_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmainaccount',
            name='fiscal_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
