# Generated by Django 5.2.4 on 2025-10-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_financialmainaccount_assembly_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='end_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start_date',
            field=models.CharField(max_length=7),
        ),
    ]
