# Generated by Django 5.2.4 on 2025-10-13 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0012_alter_unit_unique_together'),
        ('financials', '0009_accountbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='balance_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='balance_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('extraordinary', 'Extraordinary')], default='ordinary', max_length=20),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['balance_type'], name='financials__balance_725c65_idx'),
        ),
    ]
