# Generated by Django 5.2.4 on 2025-10-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_accountbalance_balance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='delinquency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
