# Generated by Django 5.2.4 on 2025-10-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_accountbalance_delinquency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='account_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='financials.financialmainaccount'),
        ),
    ]
