# Generated by Django 5.2.4 on 2025-10-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_alter_accountbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountbalance',
            name='financials__account_510c45_idx',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='notes',
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='account_name',
            field=models.CharField(max_length=200),
        ),
    ]
