# Generated by Django 5.2.4 on 2025-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_remove_accountbalance_financials__account_510c45_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmainaccount',
            name='balance_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('extraordinary', 'Extraordinary')], default='ordinary', max_length=20),
        ),
    ]
