# Generated by Django 5.2.4 on 2025-10-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_financialmainaccount_balance_type'),
    ]

    operations = [
    ]
