# Generated by Django 5.2.4 on 2025-10-22 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0012_alter_unit_unique_together'),
        ('financials', '0015_add_reference_month_to_financial_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_month', models.CharField(max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.financialmainaccount')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='building_mgmt.building')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financials_account_transaction',
                'ordering': ['-reference_month', '-created_at'],
                'indexes': [models.Index(fields=['account', 'reference_month'], name='financials__account_641565_idx'), models.Index(fields=['building', 'reference_month'], name='financials__buildin_46324b_idx')],
            },
        ),
    ]
