# Generated by Django 5.2.4 on 2025-10-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_financialaccounttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='balance_name',
        ),
    ]
