# Generated by Django 5.2.4 on 2025-10-27 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0012_alter_unit_unique_together'),
        ('financials', '0017_remove_balance_name_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketValueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rental_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rental_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condominium_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condominium_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_value_setting', to='building_mgmt.building')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financials_market_value_setting',
            },
        ),
    ]
