# Generated by Django 5.2.4 on 2025-10-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_mgmt', '0009_add_repair_status_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='building_id',
            field=models.CharField(db_column='building_id', max_length=200),
        ),
    ]
