# Generated by Django 5.2.4 on 2025-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_mgmt', '0010_alter_equipment_building_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='technician_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
