# Generated by Django 5.2.4 on 2025-10-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0011_remove_has_deposit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('building', 'number')},
        ),
    ]
