# Generated by Django 5.2.4 on 2025-10-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0002_consumptionaccount_consumptionregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('gas', 'Gas')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consumptions_sub_account',
                'ordering': ['utility_type', 'name'],
                'unique_together': {('utility_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='consumptionregister',
            name='sub_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_registers', to='consumptions.subaccount'),
        ),
    ]
