# Generated by Django 5.2.4 on 2025-10-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0003_subaccount_consumptionregister_sub_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptionregister',
            name='gas_category',
        ),
    ]
