# Generated by Django 5.2.4 on 2025-10-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0005_consumptionregister_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionregister',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
