# Generated by Django 5.2.4 on 2025-10-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0006_alter_consumptionregister_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionaccount',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consumptionaccount',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
