# Generated by Django 5.2.4 on 2025-12-15 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_mgmt', '0012_alter_unit_unique_together'),
        ('consumptions', '0007_consumptionaccount_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consumptionaccount',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_accounts', to='building_mgmt.building'),
        ),
        migrations.AddField(
            model_name='consumptionaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumptionregister',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='building_mgmt.building'),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subaccount',
            unique_together={('building', 'utility_type', 'name')},
        ),
    ]
